apiVersion: apps/v1
kind: Deployment
metadata:
  name: issabel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issabel
  template:
    metadata:
      labels:
        app: issabel
    spec:
      hostNetwork: true
      # Bypasses the "Interactive" hang by providing a TTY
      tty: true
      stdin: true
      initContainers:
      - name: fix-system-files
        image: busybox
        command: ['sh', '-c', 'mkdir -p /mnt/etc/sysconfig && touch /mnt/etc/sysconfig/network']
        volumeMounts:
        - name: etc-dir
          mountPath: /mnt/etc
      containers:
      - name: issabel
        image: renatosiqueira/issabel:latest
        securityContext:
          privileged: true 
        volumeMounts:
        - name: cgroups
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: run-dir
          mountPath: /run
        - name: etc-dir
          mountPath: /etc
      volumes:
      - name: cgroups
        hostPath:
          path: /sys/fs/cgroup
      - name: run-dir
        hostPath:
          path: /run
      - name: etc-dir
        emptyDir: {} # This keeps the /etc fixes local to the pod
